In [ ]:
import pandas as pd
import numpy as np
import nltk
import re

In [ ]:
df = pd.read_csv('sample_data/all_gp_comments4.csv', 
                 encoding='utf-8"',engine = 'python', encoding_errors='ignore')

In [ ]:
df.head(3)

,content,Unnamed: 1,Unnamed: 2,Unnamed: 3,q9.numeric,q10.numeric,q11.numeric,q12.numeric,q13.numeric,q14.numeric,Average,Sentiment
0,A nice clean friendly surgery I certainly woul...,NaN,NaN,NaN,5.0,4.0,5.0,5.0,NaN,NaN,3.166667,Neutral
1,I have been a patient at the surgery since i w...,NaN,NaN,NaN,5.0,5.0,5.0,5.0,NaN,NaN,3.333333,Neutral
2,I am doing all the leg work to get the care i ...,NaN,NaN,NaN,4.0,3.0,3.0,2.0,NaN,NaN,2.000000,Negative

In [ ]:
len(df)

208287

In [ ]:
df.isnull().sum()

content             0
Unnamed: 1     208287
Unnamed: 2     208287
Unnamed: 3     208287
q9.numeric       6572
q10.numeric      6070
q11.numeric      4851
q12.numeric     11010
q13.numeric      7092
q14.numeric     10412
Average             0
Sentiment           0
dtype: int64

In [ ]:
df = df.drop('Unnamed: 1', axis = 1)

In [ ]:
df = df.drop('Unnamed: 2', axis = 1)

In [ ]:
df = df.drop('Unnamed: 3', axis = 1)

In [ ]:
df = df.drop('q9.numeric', axis = 1)

In [ ]:
df = df.drop('q10.numeric', axis = 1)

In [ ]:
df = df.drop('q11.numeric', axis = 1)

In [ ]:
df = df.drop('q12.numeric', axis = 1)

In [ ]:
df = df.drop('q13.numeric', axis = 1)

In [ ]:
df = df.drop('q14.numeric', axis = 1)

In [ ]:
df = df.drop('Average', axis = 1)

In [ ]:
df.head(50)

                                              content Sentiment
0   A nice clean friendly surgery I certainly woul...   Neutral
1   I have been a patient at the surgery since i w...   Neutral
2   I am doing all the leg work to get the care i ...  Negative
3   I joined this doctors from another in north Lo...  Negative
4   The Doctors and staff at the practice are very...  Negative
5   First of all the contact number for this surge...  Negative
6   i have been a patient for some years and unfor...  Negative
7   This is an Outstanding Medical Centre, with ex...   Neutral
8   I can not find fault with any of the Doctors ,...  Negative
9     When it first opened this was a lovely surgery.  Negative
10  I find this surgery excellent.  I particularly...  Positive
11  Been waiting since Friday for medication sent ...  Negative
12  Prescription are never done and have to go bac...  Negative
13  No complaints about the medical profession jus...  Negative
14  New to surgery, we missed a couple of our appo...  Negative
15  Today I accompanied a relative in visiting thi...  Negative
16  Today (15.4.2013), I spoke face to face with m...  Negative
17  My family and myself are patients of the docto...  Positive
18  Ive had nothing but a first class experience o...  Positive
19  Hi,    I have found the staff at the surgery e...  Positive
20  Even if the availablity of flu vaccinations is...   Neutral
21  The only thing that is pleasant in this surger...  Negative
22  I recently went to the surgery and was waiting...  Negative
23  Visited this surgery with an elderly relative ...  Negative
24  Were looking to move after several bad experie...  Negative
25  The doctor is excellent in this practise ,me a...   Neutral
26  This surgery is the worst one I have ever been...  Negative
27  Telephone staff are very rude, I challenge thi...  Negative
28  Good Doctors at the surgery shame the receptio...  Negative
29  I tried to call surgery couple of time in the ...  Negative
30  Very surprised and shocked at the negative vie...  Positive
31    The telephone receptionists  have no trainin...  Negative
32  I would like to take the opportunity to recomm...  Positive
33  Terribly difficult to make appointments by pho...  Negative
34  Some months ago the practice changed their app...  Negative
35  Very polite staff, and an excellent consultant...  Positive
36  The staff at Croft Surgery are always extremel...  Positive
37  Used this service today as a walk-in patient. ...  Positive
38  17 years  I have been treated by the doctor.Em...  Positive
39  isPermaLink="false">191556</guid><link>http://...  Negative
40  I have rung the practice today at 3.30pm to ge...  Negative
41  This Surgery has always provided me with excel...  Positive
42  I attended the surgery to order a prescription...  Negative
43  The service has always been very good, as far ...   Neutral
44  Good people, nice new building, but it does gi...   Neutral
45  I have been a patient at this surgery since ne...  Negative
46  A polite, respectful and friendly service prov...  Positive
47  Always poor reception staff, they need trainin...   Neutral
48  I took my son here so his leg could be assesse...  Negative
49  I had a call back from my GP last Thursday, (1...  Positive

In [ ]:
df.columns = ['comment', 'sentiment']

In [ ]:
df.head(50)

                                              comment sentiment
0   A nice clean friendly surgery I certainly woul...   Neutral
1   I have been a patient at the surgery since i w...   Neutral
2   I am doing all the leg work to get the care i ...  Negative
3   I joined this doctors from another in north Lo...  Negative
4   The Doctors and staff at the practice are very...  Negative
5   First of all the contact number for this surge...  Negative
6   i have been a patient for some years and unfor...  Negative
7   This is an Outstanding Medical Centre, with ex...   Neutral
8   I can not find fault with any of the Doctors ,...  Negative
9     When it first opened this was a lovely surgery.  Negative
10  I find this surgery excellent.  I particularly...  Positive
11  Been waiting since Friday for medication sent ...  Negative
12  Prescription are never done and have to go bac...  Negative
13  No complaints about the medical profession jus...  Negative
14  New to surgery, we missed a couple of our appo...  Negative
15  Today I accompanied a relative in visiting thi...  Negative
16  Today (15.4.2013), I spoke face to face with m...  Negative
17  My family and myself are patients of the docto...  Positive
18  Ive had nothing but a first class experience o...  Positive
19  Hi,    I have found the staff at the surgery e...  Positive
20  Even if the availablity of flu vaccinations is...   Neutral
21  The only thing that is pleasant in this surger...  Negative
22  I recently went to the surgery and was waiting...  Negative
23  Visited this surgery with an elderly relative ...  Negative
24  Were looking to move after several bad experie...  Negative
25  The doctor is excellent in this practise ,me a...   Neutral
26  This surgery is the worst one I have ever been...  Negative
27  Telephone staff are very rude, I challenge thi...  Negative
28  Good Doctors at the surgery shame the receptio...  Negative
29  I tried to call surgery couple of time in the ...  Negative
30  Very surprised and shocked at the negative vie...  Positive
31    The telephone receptionists  have no trainin...  Negative
32  I would like to take the opportunity to recomm...  Positive
33  Terribly difficult to make appointments by pho...  Negative
34  Some months ago the practice changed their app...  Negative
35  Very polite staff, and an excellent consultant...  Positive
36  The staff at Croft Surgery are always extremel...  Positive
37  Used this service today as a walk-in patient. ...  Positive
38  17 years  I have been treated by the doctor.Em...  Positive
39  isPermaLink="false">191556</guid><link>http://...  Negative
40  I have rung the practice today at 3.30pm to ge...  Negative
41  This Surgery has always provided me with excel...  Positive
42  I attended the surgery to order a prescription...  Negative
43  The service has always been very good, as far ...   Neutral
44  Good people, nice new building, but it does gi...   Neutral
45  I have been a patient at this surgery since ne...  Negative
46  A polite, respectful and friendly service prov...  Positive
47  Always poor reception staff, they need trainin...   Neutral
48  I took my son here so his leg could be assesse...  Negative
49  I had a call back from my GP last Thursday, (1...  Positive

In [ ]:
df.sentiment.value_counts()

Positive    95457
Negative    93343
Neutral     19487
Name: sentiment, dtype: int64

In [ ]:
df = df[df.sentiment != "I can't tell"]

In [ ]:
X = df['comment']
y = df['sentiment']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2)

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = .2)

In [ ]:
print("Training set size:", len(X_train))
print("Validation set size:", len(X_val))
print("Test set size:", len(X_test))

Training set size: 133303
Validation set size: 33326
Test set size: 41658

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
def ascii_only(text):
    return text.encode("ascii", "ignore").decode()

In [ ]:
def make_lower(text):
    return text.lower()

In [ ]:
# Find links and remove them

def remove_links(text):
    p = '((http\w*:\/\/)?(www\.\w+)?(\w+\.(com|co|ly|ch|org|net)+)(\/\w+)?)'
    return re.sub(p, ' ', text)

In [ ]:
# Remove html symbol
def remove_html(text):
    return re.sub("[^A-Za-z0-9 ]\w+", ' ', text)

In [ ]:
# Remove mentions
def remove_mentions(text):
    return re.sub("(@\w*)", ' ', text)

In [ ]:
# Remove unnecessary punctuations
import string
punctuations = string.punctuation
punctuations = punctuations + '�' + string.digits

def remove_punctuations(text, punctuations):
    table_ = str.maketrans('', '', punctuations)
    return text.translate(table_)

In [ ]:
def remove_brandwords(text):
    p = '''#?(iphone|ipad|sxsw|hcsm|google|apple|cisco|austin|
    atari|intel|mac|pc|blackberry|android|linux|ubuntu)[a-z0-9]*'''
    return re.sub(p, ' ', text)

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

sw = (stopwords.words('english'))

def lemmatize(x, sw):
    wnl = WordNetLemmatizer()
    return ' '.join([wnl.lemmatize(w) for w in x.split() if w not in sw])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
def preprocessing(df, punctuations, stopwords):
    df['comment'] = df.comment.apply(lambda x: ascii_only(x))
    df['comment'] = df.comment.apply(lambda x: make_lower(x))
    df['comment'] = df.comment.apply(lambda x: remove_links(x))
    df['comment'] = df.comment.apply(lambda x: remove_html(x))
    df['comment'] = df.comment.apply(lambda x: remove_mentions(x))
    df['comment'] = df.comment.apply(lambda x: remove_punctuations(x, punctuations))
    df['comment'] = df.comment.apply(lambda x: remove_brandwords(x))
    df['comment'] = df.comment.apply(lambda x: lemmatize(x, sw))
    
    return df

In [ ]:
import nltk
nltk.download('wordnet')
dataset = preprocessing(pd.DataFrame(df), punctuations, sw)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
dataset.head(100)

                                              comment sentiment
0   nice clean friendly surgery certainly would re...   Neutral
1   patient surgery since born family staff always...   Neutral
2                leg work get care recieving hill way  Negative
3   joined doctor another north lowestoft recieved...  Negative
4   doctor staff practice caring asked see practic...  Negative
..                                                ...       ...
95  ive registered year lived place recommend surg...  Positive
96  ive practise year always professional good app...  Positive
97  ive recently registered family surgery recepti...  Positive
98  practice year ever recieved highly professiona...  Positive
99  four different surgery past surgery far best s...  Positive

[100 rows x 2 columns]

In [ ]:
dataset.to_csv(r'preprocessed_all_gp_comments4.csv', index=True)